# Generated by Django 4.0 on 2022-01-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='hood',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hood',
            name='fire_department',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hood',
            name='hospital_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hood',
            name='security_department',
            field=models.IntegerField(null=True),
        ),
    ]
