# Generated by Django 4.0 on 2021-12-26 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_hood_host_hood_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hood',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='hood',
            name='occupants',
            field=models.ManyToManyField(blank=True, related_name='occupants', to=settings.AUTH_USER_MODEL),
        ),
    ]
