# Generated by Django 4.0 on 2022-01-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_hood_biashara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='biashara',
            field=models.ManyToManyField(blank=True, to='app.Business'),
        ),
    ]
