# Generated by Django 4.0 on 2022-01-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_hood_biashara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='biashara',
            field=models.ManyToManyField(blank=True, related_name='biashara', to='app.Business'),
        ),
    ]
